config/routes.rb
Concept::Application.routes.draw do
  devise_for :users

  resources :photos do
    resources :comments
  end
  match 'questions/:id/upload' => 'photos#upload', :via => 'post', :as => :upload
    
  # post comment
  post 'comments/create'
  
  # tagged
  match 'tagged/:tag' => 'tagged#index', :via => 'get', :as => :tagged

  resources :questions do
    resources :comments
    get :autocomplete_tag_name, :on => :collection
  end
  
  root :to => "questions#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :photoable, :polymorphic => true
  belongs_to :user
  belongs_to :question
  
  acts_as_commentable
  acts_as_voteable
  
  scope :temphotos, lambda { where(["photoable_id IS NULL"]) }
  has_attached_file :item,
                    :storage => :s3,
                    :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
                    :path => "/delicious/:id_:style.:extension",
                    :dependent => :destroy,
                    :styles => {
                      :square   => "75x75#",
                      :thumb    => "100x75>",
                      :large    => "640x480>"
                    }
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :photos, :as => :photoable, :dependent => :destroy
  accepts_nested_attributes_for :photos
  
  acts_as_taggable
  acts_as_taggable_on :tags
  
  protected
    def self.new_one
      question = self.new
      question.photos.build
      return question
    end
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :questions, :dependent => :destroy
  has_many :photos, :dependent => :destroy
  
  acts_as_voter
  has_karma(:questions, :as => :user)
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable

  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def set_voted(someone)
    someone.voted = someone.plusminus
    someone.save
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    if params[:question_id]
      @someone = Question.find params[:question_id]
    else
      @someone = Photo.find params[:photo_id]
    end
  end

  def create
    @commentable = params[:commentable].to_s.classify.constantize
		@someone = @commentable.find(params[:id])
    @comment = @someone.comments.create(:user_id  => current_user.id, :body => params[:body].to_s)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!
  
  def upload
    @question = Question.find(params[:id])
    current_user.photos.temphotos.each do |photo|
      photo.photoable_id = @question.id
      photo.photoable_type = 'Question'
      photo.save
    end
    redirect_to @question
  end

  def create
    @photo = Photo.new(:item => params[:Filedata])
    @photo.item_content_type = MIME::Types.type_for(@photo.item_file_name).to_s
    @photo.user_id = current_user.id
    if @photo.save
      render :json => { :img_url => @photo.item.url(:thumb), :img_id => @photo.id }.to_json
    end
  end
  
  def update
    @photo = Photo.find(params[:id])
    @photo.update_attributes(:body => params[:photo][:body])
  end
  
  def show
    @photo = Photo.find(params[:id])
  end
  
  def destroy
    photo = Photo.find(params[:id])
    @img_id = photo.id
    
    photo.destroy
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :find_self_question, :only => [:edit, :update, :destroy]
  
  autocomplete :tag, :name, :full => true
  
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end
  
  def new
    @question = Question.new_one
  end

  def create
    @question = current_user.questions.build(params[:question])
    if @question.save
      current_user.photos.temphotos.each do |photo|
        photo.photoable_id = @question.id
        photo.photoable_type = 'Question'
        photo.save
      end
      redirect_to @question
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @question.update_attributes(params[:question])
      current_user.photos.temphotos.each do |photo|
        photo.photoable_id = @question.id
        photo.photoable_type = 'Question'
        photo.save
      end
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url
  end

  protected
    def find_self_question
      @question = current_user.questions.find(params[:id])
    end
end

app/controllers/tagged_controller.rb
class TaggedController < ApplicationController
  def index
    @questions = Question.tagged_with(params[:tag])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def vote_up
    @voteable = params[:voteable].to_s.classify.constantize
		@voted = @voteable.find(params[:id])
		current_user.vote_exclusively_for @voted
		set_voted @voted
  end

  def vote_down
    @voteable = params[:voteable].to_s.classify.constantize
		@voted = @voteable.find(params[:id])
		current_user.vote_exclusively_against @voted
		set_voted @voted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tagged_helper.rb
module TaggedHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<%=form_tag({:controller => 'comments', :action => 'create'}, :remote => true, :id => 'new_comment') do %>
	<%= hidden_field_tag :commentable, commentable %>
	<%= hidden_field_tag :id, id %>
	<%= text_area_tag :body, {}, :class => 'comment_area' %>
	<div class="comment_reply">
		<%= submit_tag 'Reply', :class => 'small_submit' %>
	</div>
<% end %>

app/views/comments/_show_comment.html.erb
<div id="comment_<%= show_comment.id %>" class="comment">
	<div class="comment-text">
		<%= show_comment.body %>
		<span style="color:gray"> by <%= show_comment.user.name %> - <%= time_ago_in_words show_comment.created_at %></span>
	</div>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @someone.class.name %>_<%= @someone.id %>').append("<%= escape_javascript(render :partial => 'comments/show_comment', :object => @comment) %>");
$('#new_comment')[0].reset();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concept</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag ['jquery', 'ui', 'rails', 'uploadify', 'application'] %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="container">
		<div id="header">
			<% if user_signed_in? %>
				<%= current_user.email %> or 
				<%= link_to "Sign out", destroy_user_session_path %>
				<%= link_to "Upload", new_question_path %>
			<% else %>
				<%= link_to "Sign up", new_user_registration_path %> or  
			    <%= link_to "Sign in", new_user_session_path %>
			<% end %>
		</div>
		<div id="wrapper">
			<%= yield %>
		</div>
		<div id="footer">
		</div>
	</div>
</body>
</html>

app/views/partials/_add_photo_body.html.erb
<div class="add_photo_body_form" style="display:none">
	<%= form_for(photo, :remote => true) do |f| %>
		<%= f.text_area :body, :class => "add_photo_body" %>
		<%= f.submit 'Post', :class => 'small_submit' %>
	<% end -%>
</div>

app/views/partials/_answer.html.erb
<div class="answer">
	<%= render 'partials/each_photo_for_answer', :someone => answer %>
	<%= render 'partials/comment', :someone => answer %>
</div>

app/views/partials/_comment.html.erb
<div id="comments_<%= someone.class.name %>_<%= someone.id %>" class="comments">
	<%= render :partial => "comments/show_comment", :collection => someone.comments %>
</div>
<div id="form_for_comment_<%= someone.class.name %>_<%= someone.id %>" class="form_for_comment">
	<%= render :partial => "comments/comment", :locals => {:commentable => someone.class.name, :id => someone.id} %>
</div>

app/views/partials/_each_photo.html.erb
<% someone.photos.each do |photo| %>
	<%= div_for photo do %>
		<%= image_tag photo.item.url(:large) %>
		<div class='photo_body' id='<%= photo.id %>'>
			<%= render :partial => '/partials/show_photo_body', :locals => {:photo => photo} %>
			<%= render :partial => '/partials/add_photo_body', :locals => {:photo => photo} %>
		</div>
	<% end -%>
<% end -%>

app/views/partials/_each_photo_for_answer.html.erb
<% someone.photos.each do |photo| %>
	<%= div_for photo do %>
		<%= render 'partials/vote', :someone => someone %>
		<%= image_tag photo.item.url(:large) %>
		<div class='photo_body' id='<%= photo.id %>'>
			<%= render :partial => '/partials/show_photo_body', :locals => {:photo => photo} %>
			<%= render :partial => '/partials/add_photo_body', :locals => {:photo => photo} %>
		</div>
	<% end -%>
<% end -%>

app/views/partials/_preview.html.erb
<div id="preview">
	<%= image_tag photo.item.url(:large) %>
</div>
<div id="reply">
	<%= render 'partials/comment', :someone => photo %>
</div>

app/views/partials/_question.html.erb
<%= div_for question do %>
	<div class='status'>
		<div class='username'><%= question.user.name %></div>
		<div class='postime' title='<%= question.created_at.strftime("%H:%M %m/%d/%Y") %>'><%= time_ago_in_words question.created_at %></div>
	</div>
	<div class='excerpt'>
		<%= link_to truncate(question.body, :length => 140), question %>
	</div>
	<div class='thumbs'>
		<% question.photos.limit(8).each do |photo| %>
			<%= image_tag photo.item.url(:square) %>
		<% end -%>
	</div>
	<div class="tags">
		<% question.tag_list.each do |tag| %>
			<div class="tag"><%=link_to tag, tagged_url(:tag => tag) %></div>
		<% end -%>
	</div>
<% end -%>

app/views/partials/_show_photo_body.html.erb
			<div class='photo_body_text'>
				<%= photo.body %>
			</div>

app/views/partials/_upload.html.erb
<%= f.fields_for :photos do |p| %>
	<%= p.file_field :item, :class => 'item' %>
<% end %>

app/views/partials/_upload_area.html.erb
<div id="upload_area">
	<h3>Uploaded</h3>
	<% current_user.photos.temphotos.each do |photo| %>
		<div class="uploaded_image" id="<%= photo.id %>">
			<div class="image_self">
				<%= image_tag photo.item.url(:thumb), :id => photo.id %>
			</div>
			<div class="image_ops">
				<%= link_to 'remove', photo, :method => :delete, :remote => true %>
			</div>
		</div>
	<% end -%>
</div>

app/views/partials/_vote.html.erb
<div class='vote_area'>
	<%= link_to '+', {:controller => :votes, :action => :vote_up, :voteable => someone.class.name, :id => someone.id}, :remote => true, :class => 'link_submit' %>
	<div class='vote_number' id="vote_<%= someone.class.name %>_<%= someone.id %>"><%= someone.voted %></div>
	<%= link_to '-', {:controller => :votes, :action => :vote_down, :voteable => someone.class.name, :id => someone.id}, :remote => true, :class => 'link_submit' %>
</div>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.js.erb
$("#<%=@img_id%>").remove();

app/views/photos/show.js.erb
$('#preview_page').html("<%=escape_javascript(render 'partials/preview', :photo => @photo)%>");

app/views/photos/update.js.erb
$("#<%=@photo.id%>").children('.photo_body_text').html("<%=@photo.body%>");
$("#<%=@photo.id%>").children('.photo_body_text').css('display','block');
$("#<%=@photo.id%>").children('.add_photo_body_form').css('display','none');

app/views/questions/_question.html.erb
<%= render :partial => 'upload_js' %>
<%= form_for @question, :html => { :multipart => true } do |f| %>
	<h3>Description</h3>
	<%= f.text_area :body, :class => 'area' %>
	<h3>Tags</h3>
	<%= f.text_field :tag_list, :autocomplete => autocomplete_tag_name_questions_path, :class => 'field' %>
	<div class='form_ops'>
		<%= f.submit 'Post Your Question', :class => 'submit' %>
		<div class='uploader'>
			<%= render '/partials/upload', :f => f %>
		</div>
	</div>
<% end %>

app/views/questions/_upload_js.html.erb
<script type="text/javascript">
<% session_key_name = Rails.application.config.session_options[:key] %>
$(function(){

  var uploadify_script_data = {};

  // Fetch the CSRF meta tag data
  var csrf_token = $('meta[name=csrf-token]').attr('content');
  var csrf_param = $('meta[name=csrf-param]').attr('content');

  // Now associate the data in the config, encoding the data safely
  uploadify_script_data[csrf_token] = encodeURI(encodeURIComponent(csrf_param));

  // Associate the session information
  uploadify_script_data['<%= session_key_name %>'] = '<%= cookies[session_key_name] %>';

  $('.item').uploadify({
	uploader	: '/images/uploadify.swf',
	cancelImg	: '/images/cancel.png',
	script 		: '/photos/',
	auto		: true,
	multi		: true,
	scriptData	: uploadify_script_data,
	onComplete	: function(event,queueID,fileObj,response,data) {
		response = eval('(' + response + ')');
		$('#upload_area').append("<div class='uploaded_image' id='"+response.img_id+"'><div class='image_self'><img src='"+response.img_url+"' id='"+response.img_id+"'></img></div><div class='image_ops'><a href='/photos/"+response.img_id+"' data-method='delete' data-remote='true' rel='nofollow'>remove</a></div></div>");
	}
  });
});
</script>

app/views/questions/edit.html.erb
<%= render 'question' %>
<div class="poof"></div>
<div class="section">
	<h2>已上传的图片</h2>
</div>
<div id="upload_images" class="image">
	<% @question.photos.each do |photo| %>
			<div class="uploaded_image" id="<%= photo.id %>">
				<div class="image_self">
					<%= image_tag photo.item.url(:thumb), :id => photo.id %>
				</div>
				<div class="image_ops">
					<%= link_to '删除', photo, :method => :delete, :remote => true, :class => 'deleteme' %>
				</div>
			</div>
	<% end -%>
	<div class="section">
		<h2>新上传的图片</h2>
	</div>
	<% current_user.photos.temphotos.each do |photo| %>
			<div class="uploaded_image" id="<%= photo.id %>">
				<div class="image_self">
					<%= image_tag photo.item.url(:thumb), :id => photo.id %>
				</div>
				<div class="image_ops">
					<%= link_to '删除', photo, :method => :delete, :remote => true %>
				</div>
			</div>
	<% end -%>
</div>
<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div id='content'>
	<%= render :partial => 'partials/question', :collection => @questions %>
</div>

app/views/questions/new.html.erb
<%= javascript_include_tag 'ac' %>
<%= render 'question' %>
<%= render :partial => '/partials/upload_area' %>

app/views/questions/show.html.erb
<div id='entry'>
	<div class='status'>
		<div class='username'><%= @question.user.name %></div>
		<div class='postime'><%= time_ago_in_words @question.created_at %></div>
	</div>
	<div class='post'>
		<%= @question.body %>
	</div>
</div>
<div id='view'>
	<div id='photo_thumbs'>
		<% @question.photos.each do |photo| %>
			<%= link_to image_tag(photo.item.url(:square)), photo, :remote => true %>
		<% end -%>
	</div>
	<div id="preview_page">
	</div>
</div>
<%= render :partial => 'upload_js' %>
<%= form_tag({:controller => 'photos', :action => 'upload'}, :html => { :multipart => true }) do |f| %>
	<div class='form_ops'>
		<%= submit_tag 'Upload My Images', :class => 'submit' %>
		<div class='uploader'>
		<%= file_field_tag :item, :class => 'item' %>
		</div>
	</div>
<% end %>
<%= render :partial => '/partials/upload_area' %>

app/views/tagged/index.html.erb
<%= render :partial => 'partials/question', :collection => @questions %>

app/views/votes/vote_down.js.erb
$('#vote_<%=@voteable%>_<%=@voted.id%>').html("<%= @voted.plusminus %>");

app/views/votes/vote_up.js.erb
$('#vote_<%=@voteable%>_<%=@voted.id%>').html("<%= @voted.plusminus %>");